package mod.maxbogomol.wizards_reborn.registry.common;

import mod.maxbogomol.wizards_reborn.WizardsReborn;
import mod.maxbogomol.wizards_reborn.api.spell.Spell;
import mod.maxbogomol.wizards_reborn.api.spell.SpellHandler;
import mod.maxbogomol.wizards_reborn.common.spell.aura.*;
import mod.maxbogomol.wizards_reborn.common.spell.block.*;
import mod.maxbogomol.wizards_reborn.common.spell.charge.*;
import mod.maxbogomol.wizards_reborn.common.spell.fog.MorSwarmSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.BlinkSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.CrystalCrushingSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.WisdomSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.cloud.RainCloudSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.cloud.ToxicRainSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.entity.*;
import mod.maxbogomol.wizards_reborn.common.spell.look.strike.IncinerationSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.strike.RenunciationSpell;
import mod.maxbogomol.wizards_reborn.common.spell.look.strike.RepentanceSpell;
import mod.maxbogomol.wizards_reborn.common.spell.projectile.*;
import mod.maxbogomol.wizards_reborn.common.spell.ray.*;
import mod.maxbogomol.wizards_reborn.common.spell.self.AirFlowSpell;
import mod.maxbogomol.wizards_reborn.common.spell.self.FireShieldSpell;
import mod.maxbogomol.wizards_reborn.common.spell.self.HeartOfNatureSpell;
import mod.maxbogomol.wizards_reborn.common.spell.self.WaterBreathingSpell;
import mod.maxbogomol.wizards_reborn.common.spell.sound.BoomSoundSpell;
import mod.maxbogomol.wizards_reborn.common.spell.sound.MoaiSoundSpell;
import mod.maxbogomol.wizards_reborn.common.spell.sound.PipeSoundSpell;

import java.awt.*;

public class WizardsRebornSpells {
    public static Color earthSpellColor = new Color(138, 201, 123);
    public static Color waterSpellColor = new Color(152, 180, 223);
    public static Color airSpellColor = new Color(230, 173, 134);
    public static Color fireSpellColor = new Color(225, 127, 103);
    public static Color voidSpellColor = new Color(175, 140, 194);
    public static Color frostSpellColor = new Color(221, 243, 254);
    public static Color holySpellColor = new Color(255, 248, 194);
    public static Color curseSpellColor = new Color(203, 194, 255);
    public static Color poisonSpellColor = new Color(149, 255, 115);
    public static Color witheringSpellColor = new Color(64, 50, 41);
    public static Color necroticSpellColor = new Color(255, 119, 167);
    public static Color experienceSpellColor = new Color(245, 255, 143);
    public static Color soundSpellColor = new Color(250, 242, 242);

    public static Spell EARTH_PROJECTILE = new EarthProjectileSpell(WizardsReborn.MOD_ID+":earth_projectile", 5);
    public static Spell WATER_PROJECTILE = new WaterProjectileSpell(WizardsReborn.MOD_ID+":water_projectile", 5);
    public static Spell AIR_PROJECTILE = new AirProjectileSpell(WizardsReborn.MOD_ID+":air_projectile", 5);
    public static Spell FIRE_PROJECTILE = new FireProjectileSpell(WizardsReborn.MOD_ID+":fire_projectile", 5);
    public static Spell VOID_PROJECTILE = new VoidProjectileSpell(WizardsReborn.MOD_ID+":void_projectile", 5);
    public static Spell FROST_PROJECTILE = new FrostProjectileSpell(WizardsReborn.MOD_ID+":frost_projectile", 5);
    public static Spell HOLY_PROJECTILE = new HolyProjectileSpell(WizardsReborn.MOD_ID+":holy_projectile", 5);
    public static Spell CURSE_PROJECTILE = new CurseProjectileSpell(WizardsReborn.MOD_ID+":curse_projectile", 5);
    public static Spell EARTH_RAY = new EarthRaySpell(WizardsReborn.MOD_ID+":earth_ray", 7);
    public static Spell WATER_RAY = new WaterRaySpell(WizardsReborn.MOD_ID+":water_ray", 7);
    public static Spell AIR_RAY = new AirRaySpell(WizardsReborn.MOD_ID+":air_ray", 7);
    public static Spell FIRE_RAY = new FireRaySpell(WizardsReborn.MOD_ID+":fire_ray", 7);
    public static Spell VOID_RAY = new VoidRaySpell(WizardsReborn.MOD_ID+":void_ray", 7);
    public static Spell FROST_RAY = new FrostRaySpell(WizardsReborn.MOD_ID+":frost_ray", 7);
    public static Spell HOLY_RAY = new HolyRaySpell(WizardsReborn.MOD_ID+":holy_ray", 7);
    public static Spell CURSE_RAY = new CurseRaySpell(WizardsReborn.MOD_ID+":curse_ray", 7);
    public static Spell HEART_OF_NATURE = new HeartOfNatureSpell(WizardsReborn.MOD_ID+":heart_of_nature", 8);
    public static Spell WATER_BREATHING = new WaterBreathingSpell(WizardsReborn.MOD_ID+":water_breathing", 8);
    public static Spell AIR_FLOW = new AirFlowSpell(WizardsReborn.MOD_ID+":air_flow", 8);
    public static Spell FIRE_SHIELD = new FireShieldSpell(WizardsReborn.MOD_ID+":fire_shield", 8);
    public static Spell BLINK = new BlinkSpell(WizardsReborn.MOD_ID+":blink", 8, false);
    public static Spell SNOWFLAKE = new SnowflakeSpell(WizardsReborn.MOD_ID+":snowflake", 8);
    public static Spell HOLY_CROSS = new HolyCrossSpell(WizardsReborn.MOD_ID+":holy_cross", 8);
    public static Spell CURSE_CROSS = new CurseCrossSpell(WizardsReborn.MOD_ID+":curse_cross", 8);
    public static Spell POISON = new PoisonSpell(WizardsReborn.MOD_ID+":poison", 8);
    public static Spell MAGIC_SPROUT = new MagicSproutSpell(WizardsReborn.MOD_ID+":magic_sprout", 10);
    public static Spell DIRT_BLOCK = new DirtBlockSpell(WizardsReborn.MOD_ID+":dirt_block", 4);
    public static Spell WATER_BLOCK = new WaterBlockSpell(WizardsReborn.MOD_ID+":water_block", 4);
    public static Spell AIR_IMPACT = new AirImpactSpell(WizardsReborn.MOD_ID+":air_impact", 4);
    public static Spell ICE_BLOCK = new IceBlockSpell(WizardsReborn.MOD_ID+":ice_block", 4);
    public static Spell EARTH_CHARGE = new EarthChargeSpell(WizardsReborn.MOD_ID+":earth_charge", 10);
    public static Spell WATER_CHARGE = new WaterChargeSpell(WizardsReborn.MOD_ID+":water_charge", 10);
    public static Spell AIR_CHARGE = new AirChargeSpell(WizardsReborn.MOD_ID+":air_charge", 10);
    public static Spell FIRE_CHARGE = new FireChargeSpell(WizardsReborn.MOD_ID+":fire_charge", 10);
    public static Spell VOID_CHARGE = new VoidChargeSpell(WizardsReborn.MOD_ID+":void_charge", 10);
    public static Spell FROST_CHARGE = new FrostChargeSpell(WizardsReborn.MOD_ID+":frost_charge", 10);
    public static Spell HOLY_CHARGE = new HolyChargeSpell(WizardsReborn.MOD_ID+":holy_charge", 10);
    public static Spell CURSE_CHARGE = new CurseChargeSpell(WizardsReborn.MOD_ID+":curse_charge", 10);
    public static Spell EARTH_AURA = new EarthAuraSpell(WizardsReborn.MOD_ID+":earth_aura", 12);
    public static Spell WATER_AURA = new WaterAuraSpell(WizardsReborn.MOD_ID+":water_aura", 12);
    public static Spell AIR_AURA = new AirAuraSpell(WizardsReborn.MOD_ID+":air_aura", 12);
    public static Spell FIRE_AURA = new FireAuraSpell(WizardsReborn.MOD_ID+":fire_aura", 12);
    public static Spell VOID_AURA = new VoidAuraSpell(WizardsReborn.MOD_ID+":void_aura", 12);
    public static Spell FROST_AURA = new FrostAuraSpell(WizardsReborn.MOD_ID+":frost_aura", 12);
    public static Spell HOLY_AURA = new HolyAuraSpell(WizardsReborn.MOD_ID+":holy_aura", 12);
    public static Spell CURSE_AURA = new CurseAuraSpell(WizardsReborn.MOD_ID+":curse_aura", 12);
    public static Spell RAIN_CLOUD = new RainCloudSpell(WizardsReborn.MOD_ID+":rain_cloud", 15);
    public static Spell LAVA_BLOCK = new LavaBlockSpell(WizardsReborn.MOD_ID+":lava_block", 12);
    public static Spell ICICLE = new IcicleSpell(WizardsReborn.MOD_ID+":icicle", 10);
    public static Spell SHARP_BLINK = new BlinkSpell(WizardsReborn.MOD_ID+":sharp_blink", 10, true);
    public static Spell CRYSTAL_CRUSHING = new CrystalCrushingSpell(WizardsReborn.MOD_ID+":crystal_crushing", 8);
    public static Spell TOXIC_RAIN = new ToxicRainSpell(WizardsReborn.MOD_ID+":toxic_rain", 8);
    public static Spell MOR_SWARM = new MorSwarmSpell(WizardsReborn.MOD_ID+":mor_swarm", 8);
    public static Spell WITHERING = new WitheringSpell(WizardsReborn.MOD_ID+":withering", 8);
    public static Spell IRRITATION = new IrritationSpell(WizardsReborn.MOD_ID+":irritation", 8);
    public static Spell NECROTIC_RAY = new NecroticRaySpell(WizardsReborn.MOD_ID+":necrotic_ray", 8);
    public static Spell LIGHT_RAY = new LightRaySpell(WizardsReborn.MOD_ID+":light_ray", 8);
    public static Spell INCINERATION = new IncinerationSpell(WizardsReborn.MOD_ID+":incineration", 15);
    public static Spell REPENTANCE = new RepentanceSpell(WizardsReborn.MOD_ID+":repentance", 15);
    public static Spell RENUNCIATION = new RenunciationSpell(WizardsReborn.MOD_ID+":renunciation", 15);
    public static Spell EMBER_RAY = new EmberRaySpell(WizardsReborn.MOD_ID+":ember_ray", 15);
    public static Spell WISDOM = new WisdomSpell(WizardsReborn.MOD_ID+":wisdom", 20);

    public static Spell PIPE_SOUND = new PipeSoundSpell(WizardsReborn.MOD_ID+":pipe_sound", 0);
    public static Spell BOOM_SOUND = new BoomSoundSpell(WizardsReborn.MOD_ID+":boom_sound", 0);
    public static Spell MOAI_SOUND = new MoaiSoundSpell(WizardsReborn.MOD_ID+":moai_sound", 0);

    public static void register() {
        SpellHandler.register(EARTH_PROJECTILE);
        SpellHandler.register(WATER_PROJECTILE);
        SpellHandler.register(AIR_PROJECTILE);
        SpellHandler.register(FIRE_PROJECTILE);
        SpellHandler.register(VOID_PROJECTILE);
        SpellHandler.register(FROST_PROJECTILE);
        SpellHandler.register(HOLY_PROJECTILE);
        SpellHandler.register(CURSE_PROJECTILE);
        SpellHandler.register(EARTH_RAY);
        SpellHandler.register(WATER_RAY);
        SpellHandler.register(AIR_RAY);
        SpellHandler.register(FIRE_RAY);
        SpellHandler.register(VOID_RAY);
        SpellHandler.register(FROST_RAY);
        SpellHandler.register(HOLY_RAY);
        SpellHandler.register(CURSE_RAY);
        SpellHandler.register(HEART_OF_NATURE);
        SpellHandler.register(WATER_BREATHING);
        SpellHandler.register(AIR_FLOW);
        SpellHandler.register(FIRE_SHIELD);
        SpellHandler.register(BLINK);
        SpellHandler.register(SNOWFLAKE);
        SpellHandler.register(HOLY_CROSS);
        SpellHandler.register(CURSE_CROSS);
        SpellHandler.register(POISON);
        SpellHandler.register(MAGIC_SPROUT);
        SpellHandler.register(DIRT_BLOCK);
        SpellHandler.register(WATER_BLOCK);
        SpellHandler.register(AIR_IMPACT);
        SpellHandler.register(ICE_BLOCK);
        SpellHandler.register(EARTH_CHARGE);
        SpellHandler.register(WATER_CHARGE);
        SpellHandler.register(AIR_CHARGE);
        SpellHandler.register(FIRE_CHARGE);
        SpellHandler.register(VOID_CHARGE);
        SpellHandler.register(FROST_CHARGE);
        SpellHandler.register(HOLY_CHARGE);
        SpellHandler.register(CURSE_CHARGE);
        SpellHandler.register(EARTH_AURA);
        SpellHandler.register(WATER_AURA);
        SpellHandler.register(AIR_AURA);
        SpellHandler.register(FIRE_AURA);
        SpellHandler.register(VOID_AURA);
        SpellHandler.register(FROST_AURA);
        SpellHandler.register(HOLY_AURA);
        SpellHandler.register(CURSE_AURA);
        SpellHandler.register(RAIN_CLOUD);
        SpellHandler.register(LAVA_BLOCK);
        SpellHandler.register(ICICLE);
        SpellHandler.register(SHARP_BLINK);
        SpellHandler.register(CRYSTAL_CRUSHING);
        SpellHandler.register(TOXIC_RAIN);
        SpellHandler.register(MOR_SWARM);
        SpellHandler.register(WITHERING);
        SpellHandler.register(IRRITATION);
        SpellHandler.register(NECROTIC_RAY);
        SpellHandler.register(LIGHT_RAY);
        SpellHandler.register(INCINERATION);
        SpellHandler.register(REPENTANCE);
        SpellHandler.register(RENUNCIATION);
        SpellHandler.register(EMBER_RAY);
        SpellHandler.register(WISDOM);

        SpellHandler.register(PIPE_SOUND);
        SpellHandler.register(BOOM_SOUND);
        SpellHandler.register(MOAI_SOUND);
        PIPE_SOUND.addAllCrystalType();
        BOOM_SOUND.addAllCrystalType();
        MOAI_SOUND.addAllCrystalType();
    }
}
