package mod.maxbogomol.wizards_reborn.api.arcaneenchantment;

public enum ArcaneEnchantmentTypes implements ArcaneEnchantmentType {
    ALL,
    BREAKABLE,
    CURIO,
    BOOK,
    TOOL,
    WEAPON,
    MELEE_WEAPON,
    RANGED_WEAPON,
    ARMOR,
    SWORD,
    PICKAXE,
    AXE,
    SHOVEL,
    HOE,
    SCYTHE,
    KNIFE,
    BOW,
    CROSSBOW,
    FISHING_ROD,
    SHEARS,
    HELMET,
    CHESTPLATE,
    LEGGINGS,
    BOOTS,
    WOODEN,
    ARCANE_COLD,
    SARCON,
    VILENIUM,
    ARCANE_WOOD,
    INNOCENT_WOOD,
    MAGIC_ARMOR,
    FORTRESS_ARMOR,
    INVENTOR_WIZARD_ARMOR,
    ARCANE_FORTRESS_ARMOR
}
